# Generated by Django 3.2 on 2022-04-20 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("musicblog", "0002_post_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="blog_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
